### ISSUE TITLE
Operation not permitted (Linux-based)/ PermissionERROR (Windows11)

### ISSUE THREAD

**Issue by rpisalive** [shuzhao-li-lab/PythonCentricPipelineForMetabolomics#82]
Hello shuzhao-li-lab,

Thank you for developing the tool and I am trying to use it for my metabolomics analysis.
I was trying get myself familiarise with the provided sample dataset "MT02Dataset".
After generating the basic_metadata.csv, I tried to run assemble:
"pcpfm assemble -o . -j pcpfm_tutorial_basic -s ./basic_metadata.csv"

I first ran it on a linux-based HPC to which I have remote access but received the following error messages:

_Attempting:  assemble
[Warning] Not index found and build_index_from_scratch is False
[Warning] Not index found and build_index_from_scratch is False
Error executing: assemble

        This is the first command in any pcpfm analysis. Starting with a
        sequence file, specified by '-s', an output directory by '-o'
        and a project name specified by '-j', this will create the
        experiment directory and initialize the experiment.json.

        Additional arguments include the ability to add a filter on
        sequence file entries using the '--filter' option and a JSON
        dictionaries.

        <<TODO>>

        Additionally, the --name_field, and --path_field options will
        allow the user to specify what field name should be used for the
        name and filepath of the acquisitions. Also using --skip_list and
        a .txt formatted file containing sample_names to ignore, entries
        can be excluded from an analysis.

        :param params: This is the master configuration file generated by
                    parsing the command line arguments plus the defaults.

Exception:  [Errno 1] Operation not permitted: '/MT02Dataset/batch11_MT_20210805_005.mzML' -> '/pcpfm_tutorial_basic/converted_acquisitions/batch11_MT_20210805_005.mzML'
Traceback:
Traceback (most recent call last):
  File "/.conda/envs/pcpfm/lib/python3.9/site-packages/pcpfm/main.py", line 972, in main
    function(params)
  File "/.conda/envs/pcpfm/lib/python3.9/site-packages/pcpfm/main.py", line 329, in assemble
    experiment = Experiment.Experiment.construct_experiment_from_CSV(
  File "/.conda/envs/pcpfm/lib/python3.9/site-packages/pcpfm/Experiment.py", line 640, in construct_experiment_from_CSV
    experiment.add_acquisition(acquisition, mode=file_mode)
  File "/.conda/envs/pcpfm/lib/python3.9/site-packages/pcpfm/Experiment.py", line 447, in add_acquisition
    file_operations[mode](acquisition.source_filepath, target_path)
PermissionError: [Errno 1] Operation not permitted: '/MT02Dataset/batch11_MT_20210805_005.mzML' -> '/pcpfm_tutorial_basic/converted_acquisitions/batch11_MT_20210805_005.mzML'_

Paths edited.

Later, I tried again on my personal laptop (Windows 11) and receive the following error messages:

_Attempting:  assemble
[Warning] Not index found and build_index_from_scratch is False
[Warning] Not index found and build_index_from_scratch is False
[Warning] Not index found and build_index_from_scratch is False
[Warning] Not index found and build_index_from_scratch is False
[Warning] Not index found and build_index_from_scratch is False
[Warning] Not index found and build_index_from_scratch is False
[Warning] Not index found and build_index_from_scratch is False
[Warning] Not index found and build_index_from_scratch is False
[Warning] Not index found and build_index_from_scratch is False
[Warning] Not index found and build_index_from_scratch is False
[Warning] Not index found and build_index_from_scratch is False
[Warning] Not index found and build_index_from_scratch is False
[Warning] Not index found and build_index_from_scratch is False
[Warning] Not index found and build_index_from_scratch is False
[Warning] Not index found and build_index_from_scratch is False
[Warning] Not index found and build_index_from_scratch is False
Error executing: assemble

        This is the first command in any pcpfm analysis. Starting with a
        sequence file, specified by '-s', an output directory by '-o'
        and a project name specified by '-j', this will create the
        experiment directory and initialize the experiment.json.

        Additional arguments include the ability to add a filter on
        sequence file entries using the '--filter' option and a JSON
        dictionaries.

        <<TODO>>

        Additionally, the --name_field, and --path_field options will
        allow the user to specify what field name should be used for the
        name and filepath of the acquisitions. Also using --skip_list and
        a .txt formatted file containing sample_names to ignore, entries
        can be excluded from an analysis.

        :param params: This is the master configuration file generated by
                    parsing the command line arguments plus the defaults.

Exception:  can only concatenate str (not "PermissionError") to str
Traceback:
Traceback (most recent call last):
  File "\anaconda3\envs\pcpfm\lib\shutil.py", line 825, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '\pcpfm_tutorial_basic\\experiment.json.tmp' -> '\pcpfm_tutorial_basic\\experiment.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\pcpfm\lib\site-packages\pcpfm\Experiment.py", line 218, in save
    file_operations["move"](save_path, save_path.replace(".tmp", ""))
  File "\anaconda3\envs\pcpfm\lib\shutil.py", line 846, in move
    os.unlink(src)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '\pcpfm_tutorial_basic\\experiment.json.tmp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\anaconda3\envs\pcpfm\lib\site-packages\pcpfm\main.py", line 972, in main
    function(params)
  File "\anaconda3\envs\pcpfm\lib\site-packages\pcpfm\main.py", line 329, in assemble
    experiment = Experiment.Experiment.construct_experiment_from_CSV(
  File "\anaconda3\envs\pcpfm\lib\site-packages\pcpfm\Experiment.py", line 644, in construct_experiment_from_CSV
    experiment.save()
  File "\anaconda3\envs\pcpfm\lib\site-packages\pcpfm\Experiment.py", line 220, in save
    print("Unable to save experiment!\n" + e)
TypeError: can only concatenate str (not "PermissionError") to str_

Paths edited.

The pcpfm was installed using pip, with a new virtual environment created with conda.

I tried the tutorial on the provided google colab and it worked fine, just not on my accessible machines.
After the error messages, a project file was created but obviously the assemble function is not run completely.
The experiment.json is empty.
Could you advise if there is anything I did wrong?

Thank you very much.

**Comment by rpisalive** [comment]
It looks like hards are not allowed in BeegFS file systems, I modified Experiment.py to solve the problem:

1. Add a line to import shutil - import shutil
2. modified line 447 into:
try:
    file_operations[mode](acquisition.source_filepath, target_path)
except OSError as e:
    print(f"Failed to {mode} file: {e}. Falling back to copy.")
    shutil.copy(acquisition.source_filepath, target_path)

Now the .maML files can be copied into the converted_accquisitions folder.
