### ISSUE TITLE
Bug in assemble

### ISSUE THREAD

**Issue by felipe-mansoldo** [shuzhao-li-lab/PythonCentricPipelineForMetabolomics#83]
Dear all,

I tried to reproduce the 3_advanced_pcpfm_usage.ipynb tutorial without success.
It seems that there is a bug in assemble.
See:
![image](https://github.com/user-attachments/assets/d204d78f-3569-4ca9-b442-59a2ac6bd5ff)

I'm using windows 11.
More details of the error:
```
Exception:  can only concatenate str (not "PermissionError") to str
Traceback:
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 886, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'G:\\asari_test\\pcpfm_tutorial_advanced\\experiment.json.tmp' -> 'G:\\asari_test\\pcpfm_tutorial_advanced\\experiment.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\pcpfm\Experiment.py", line 218, in save
    file_operations["move"](save_path, save_path.replace(".tmp", ""))
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 907, in move
    os.unlink(src)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'G:\\asari_test\\pcpfm_tutorial_advanced\\experiment.json.tmp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\pcpfm\main.py", line 972, in main
    function(params)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\pcpfm\main.py", line 329, in assemble
    experiment = Experiment.Experiment.construct_experiment_from_CSV(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\pcpfm\Experiment.py", line 644, in construct_experiment_from_CSV
    experiment.save()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\pcpfm\Experiment.py", line 220, in save
    print("Unable to save experiment!\n" + e)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
TypeError: can only concatenate str (not "PermissionError") to str

```

**Comment by jmmitc06** [comment]
It seems you do not have permission to run the code in or access the files
you are attempting to use. Check permissions then try again is my initial
suggestions.

**Comment by jylee3247** [comment]
Hello,

First of all, thank you for developing such a great program.

I encountered a similar problem and, after reviewing the code, discovered that in the `save` function of the `Experiment.py` file there is an issue: while the file is open, there is an attempt to rename it (line 218).

```python
try:
    save_path = os.path.join(self.experiment_directory, "experiment.json.tmp")
    with open(os.path.join(save_path), "w", encoding="utf-8") as save_filehandle:
        self.command_history.append(str(time.time()) + ":" + ";".join(sys.argv))
        json.dump(recursive_encoder(self.__dict__), save_filehandle, indent=4)
        file_operations["move"](save_path, save_path.replace(".tmp", ""))  # miss indentation?
except Exception as e:
    print("Unable to save experiment!\n" + str(e))
    raise e
```

If it was not intentional, it is likely an indentation problem

Adjusting the indentation so that the `shutil.move` function call is outside the `with` block should resolve the problem.

Sincerely,

**Comment by jmmitc06** [comment]
Thanks Jylee,

I'll look this week at this issue. Quick glance looks like you are correct.
Let me confirm and I can fix it.

**Comment by jylee3247** [comment]
Thank you for code update!

I appreciate your efforts and looking forward to the upcoming update.
